Homepage
avatartwn-devops-bootcamp
latest
10-kubernetes
demo-deploying-application
Repository
Files
f
mongo-conf
‎igmap.yaml‎
mongo-exp
‎ress.yaml‎
mongo-se
‎cret.yaml‎
mongo
‎.yaml‎
demo-deploying-application
mongo.yaml
mongo.yaml
 Nana Janashia's avatar
Starting code changes
Most recent commit.
Nana Janashia authored 22 Aug 2023
a881b9e1
mongo.yaml
302 B
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template: 
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo